language: go

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          go: 1.6
          env: CC="gcc-5" CXX="g++-5"
        - os: osx
          osx_image: xcode7.2
          go: 1.6

install:
    - go get -u github.com/smartystreets/goconvey

script:
    - make check
    - go test -v -race .
    - CGO_CFLAGS="-fsanitize=address" CGO_LDFLAGS="-fsanitize=address" go test -v .
